### ISSUE TITLE
_post function mangles Unicode filenames

### ISSUE THREAD

**Issue by geoffblack** [joesecurity/jbxapi#10]
In the `_post` function, your comment says "Remove non-ASCII characters from filenames due to a limitation of the combination of urllib3 (via python-requests) and our server." Instead of dropping all non-ASCII characters to work around web server header encoding support, you should encode the filename using `urllib.parse.quote` and then decode the filename on the server-side if necessary.

**Comment by joesecurity** [comment]
Hi geoffblack,

Thanks for the suggestion. This change would not be compatible with other users of our API.

Furtunately, a fix was just merged in https://github.com/urllib3/urllib3/pull/1492. We will revisit this once the change has been released.

**Comment by geoffblack** [comment]
I don't think it would be incompatible - you're not forced to encode if your filename is already in ASCII, though it would require a change on the server side code to support decoding the output. But it's great that urllib merged that change. Let's see how long it takes to make it to mainstream Python.

**Comment by joesecurity** [comment]
We just release jbxapi 3.1.1 which includes the updated version of urllib3. You should now be able to upload non-ascii filenames.
