### ISSUE TITLE
Need non-ascii filename support

### ISSUE THREAD

**Issue by nkh8212** [joesecurity/jbxapi#15]
Some malware does not work if it have not specific file name and sometimes it's filename is not english.
But jbxapi dose not support non-ascii filename because it use urllib3.
There are many ways to solve problems such as % encoding.
I hope jbxapi support non-ascii filename :)

**Comment by georgschoelly** [comment]
Duplicate of https://github.com/joesecurity/jbxapi/issues/10

This was fixed in urllib3 1.25.2. Once  you upgrade that package it should work automatically.
