### ISSUE TITLE
Add a command line argument to allow a custom certificate or no SSL verification

### ISSUE THREAD

**Issue by zaddach** [joesecurity/jbxapi#19]
Add a command line argument so that `ssl_verify` can be passed from the command line argument to the JoeSandbox constructor. That would allow to use the library in a development setting where a self-signed server certificate is used.

**Comment by georgschoelly** [comment]
Thanks for the feature request.

We just released version 3.7 which adds support for `--no-check-certificate` to disable certificate checking.
