### ISSUE TITLE
Manual Installation instructions typo

### ISSUE THREAD

**Issue by nksCH** [joesecurity/jbxapi#21]
Hi Joe Team
The documentation (https://github.com/joesecurity/jbxapi#manually) states to install `python-requests` using the following command:
```
pip install python-request
```
But according to the `python-requests` documentation, it should be:
```
pip install requests
```
See: https://pypi.org/project/requests/

**Comment by georgschoelly** [comment]
Thank you very much for the bug report. I pushed a fix.
