### ISSUE TITLE
create sdist for pypi

### ISSUE THREAD

**Issue by gettoknowmii** [joesecurity/jbxapi#22]
At https://pypi.org/project/jbxapi/#files there is no sdist, as is standard pypi/python practice.

Any plans to create one? It would greatly simplify the work of your downstream packagers.

Thank you.

**Comment by georgschoelly** [comment]
Thanks for the request. We will take this into account for the next release.

**Comment by georgschoelly** [comment]
We just released [jbxapi v3.17.1](https://pypi.org/project/jbxapi/3.17.1/#files) which includes an sdist.

**Comment by gettoknowmii** [comment]
Awesome! Thank you. works
