### ISSUE TITLE
Inquiry on Specifying Analysis System Using CLI in jbxapi

### ISSUE THREAD

**Issue by joseraeiro** [joesecurity/jbxapi#52]
Hello jbxapi Community,

I am currently using the jbxapi for automating malware analysis with Joe Sandbox and have encountered a question regarding the CLI usage.

I need to specify the analysis system (e.g., Windows, Linux, Mac environments) when submitting files for analysis using the CLI. While I am aware of the wide range of systems available for analysis in Joe Sandbox, I have not been able to find specific documentation or examples that detail how to set this parameter using the CLI.

Could you please provide guidance or an example on how to specify the analysis system in a CLI command? Knowing the exact syntax or parameters to use would be immensely helpful, especially for analyzing different file types in their respective environments.

Thank you in advance for your assistance and for the great work on this tool!

**Comment by georgschoelly** [comment]
You can specify the system to use on the CLI, e.g. `jbxapi --system win11`.

**Comment by joseraeiro** [comment]
And where would I find the list of accepted parameters for --system?

**Comment by georgschoelly** [comment]
Please contact our official support channels in the future, we do not frequently look at Github issues.

You can either get the system name from the GUI on the submission page, or you can also query all available systems through the CLI:

```
jbxapi server systems
[
    {
        "arch": "WINDOWS",
        "count": 8,
        "description": "...",
        "name": "w10x64_office"
    },
...
```
