### ISSUE TITLE
Unable to submit - joesandbox.com

### ISSUE THREAD

**Issue by gaiking-uk** [joesecurity/jbxapi#55]
I wanted to submit an issue that I was unable to start an analysis session on https://www.joesandbox.com however could not find anywhere to do this...
- No contact info @ https://www.joesandbox.com
- Contact form @ https://www.joesecurity.org/contact is for corporate users only
- https://twitter.com/joe4security is inactive
- No dedicated JoeSandbox repo

## Here is my analysis session...
![JoeSandbox - Can't Analyse](https://github.com/joesecurity/jbxapi/assets/37931190/4fb97ce2-d2c5-43c6-99ce-917e4ea701b5)

## For context
- Every field that can be completed was completed
- Every filed that is blank was blocked from entry (🚫when trying to select)
- I tried selecting: 0 machines (shown), 1 machine and multiple machines
- In every case, the analyse button was always greyed-out and marked as 🚫 blocked, with no indicator or help message explaining why

### Please can someone help!
If this needs to be posted in another repo, am happy to do that.

**Comment by georgschoelly** [comment]
Only logged in users can submit samples.
